version: "3"
services:
  deno-express-api:
    container_name: deno-express-api
    image: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
