basePath: /api
host: localhost:5000
info:
  contact: {}
  description: This is an API for the Shift project
  license:
    name: MIT
    url: https://mit-license.org/
  title: Shift API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Returns OK message if ther server is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get status
      tags:
      - Public
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
