basePath: /api
host: localhost:5000
info:
  contact: {}
  description: This is an API for the <codename> project
  license:
    name: MIT
    url: https://mit-license.org/
  title: Database service API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Returns a hello message. Can be used to check if the service is
        online.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Hello route
      tags:
      - Public
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
